version: '3.1'
#para roder os services abaixo
#docker-compose up -d

#para terminar os services abaixo
#docker-compose down 
services:
  mysqlEvents:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "pensealem"
      MYSQL_DATABASE: "Evently"
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge